### ISSUE TITLE
./offlinetphere and /offlineteleporthere

### ISSUE THREAD

**Issue by git0FleX** [TheBlackEntity/ServerSystem#12]
**When using the above commands, the following error occurs:
Server version used: Minecraft Purple 1.19.2**
`[14:49:13 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'offlinetphere' in plugin ServerSystem v1.7.6
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:962) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.2.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:313) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:297) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2386) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2340) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1472) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.world.entity.Entity net.minecraft.server.level.EntityPlayer.teleportTo(net.minecraft.server.level.WorldServer, net.minecraft.core.BlockPosition)'
	at me.entity303.serversystem.utils.versions.offlineplayer.teleport.Teleport_Latest.teleport(Teleport_Latest.java:56) ~[ServerSystem.jar:?]
	at me.entity303.serversystem.commands.executable.OfflineTeleportHereCommand.onCommand(OfflineTeleportHereCommand.java:60) ~[ServerSystem.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	... 23 more`

**After that the plugin spams with the following message:**
`[14:49:51 WARN]: [ServerSystem] Task #11582 for ServerSystem v1.7.6 generated an exception
java.lang.NoSuchFieldError: r
	at me.entity303.serversystem.utils.versions.offlineplayer.data.SaveData_Latest.saveData(SaveData_Latest.java:63) ~[ServerSystem.jar:?]
	at me.entity303.serversystem.utils.MessageUtils.lambda$getHookedPlayer$0(MessageUtils.java:29) ~[ServerSystem.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer$ByteBuddy$z9zvQ7Ai.saveData(Unknown Source) ~[?:?]
	at me.entity303.serversystem.commands.executable.OfflineInvseeCommand.lambda$onCommand$0(OfflineInvseeCommand.java:146) ~[ServerSystem.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by TheBlackEntity** [comment]
Fixed in future version, will update soon

**Comment by TheBlackEntity** [comment]
Please update to the latest version now
