### ISSUE TITLE
Amboss crashes the server (1.19.4)

### ISSUE THREAD

**Issue by DampfWaffel** [TheBlackEntity/ServerSystem#13]
Hello,

when using the command `/amboss` the server crashes after exiting the gui.

sehr toll. :)
Server: Purpur 1.19.4
Plugin: newest from spigot 1.7.7

```
[12:45:36 INFO]: Vertragspartner issued server command: /amboss
[12:45:36 WARN]: java.lang.reflect.InvocationTargetException
[12:45:36 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
[12:45:36 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[12:45:36 WARN]:        at ServerSystem.jar//me.entity303.serversystem.virtual.anvil.VirtualAnvil_Latest.openAnvil(VirtualAnvil_Latest.java:152)
[12:45:36 WARN]:        at ServerSystem.jar//me.entity303.serversystem.commands.executable.AnvilCommand.onCommand(AnvilCommand.java:28)
[12:45:36 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:45:36 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[12:45:36 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:920)
[12:45:36 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[12:45:36 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[12:45:36 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:330)
[12:45:36 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:314)
[12:45:36 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2382)
[12:45:36 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$21(PlayerConnection.java:2342)
[12:45:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[12:45:36 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)[12:45:36 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:45:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[12:45:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[12:45:36 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1369)
[12:45:36 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[12:45:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[12:45:36 WARN]:        at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1346)
[12:45:36 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1339)
[12:45:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[12:45:36 WARN]:        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1317)
[12:45:36 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1205)
[12:45:36 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
[12:45:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1623)
[12:45:36 WARN]: Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.core.BlockPosition.<init>(double, double, double)'
[12:45:36 WARN]:        at ServerSystem.jar//me.entity303.serversystem.virtual.containeraccess.ContainerAccess_Latest.getPosition(ContainerAccess_Latest.java:68)
[12:45:36 WARN]:        at net.minecraft.world.inventory.ContainerAccess.getLocation(ContainerAccess.java:21)
[12:45:36 WARN]:        at net.minecraft.world.inventory.ContainerAnvil.getBukkitView(ContainerAnvil.java:430)
[12:45:36 WARN]:        at net.minecraft.world.inventory.ContainerAnvil.getBukkitView(ContainerAnvil.java:31)
[12:45:36 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[12:45:36 WARN]:        ... 27 more
[12:45:37 ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'void net.minecraft.core.BlockPosition.<init>(double, double, double)'
        at me.entity303.serversystem.virtual.containeraccess.ContainerAccess_Latest.getPosition(ContainerAccess_Latest.java:68) ~[ServerSystem.jar:?]
        at net.minecraft.world.inventory.ContainerLevelAccess.getLocation(ContainerLevelAccess.java:21) ~[?:?]
        at net.minecraft.world.inventory.AnvilMenu.getBukkitView(AnvilMenu.java:430) ~[?:?]
        at net.minecraft.world.inventory.AnvilMenu.getBukkitView(AnvilMenu.java:31) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1577) ~[purpur-1.19.4.jar:git-Purpur-1962]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:3049) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:3042) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.a(ServerboundContainerClosePacket.java:10) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.4.jar:git-Purpur-1962]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1369) ~[purpur-1.19.4.jar:git-Purpur-1962]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.4.jar:git-Purpur-1962]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1346) ~[purpur-1.19.4.jar:git-Purpur-1962]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1339) ~[purpur-1.19.4.jar:git-Purpur-1962]        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1317) ~[purpur-1.19.4.jar:git-Purpur-1962]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1205) ~[purpur-1.19.4.jar:git-Purpur-1962]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1962]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[12:45:38 ERROR]: This crash report has been saved to: C:\Users\Autobahn\Desktop\Test Server\.\crash-reports\crash-2023-04-16_12.45.38-server.txt

**Comment by TheBlackEntity** [comment]
Please update to the latest ServerSystem version
