### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Michotek** [TheBlackEntity/ServerSystem#6]
Everytime I join server it kicks me without reason, error that apprears in console:
[16:00:11 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.setAccessible(boolean)" because "this.field" is null
[16:00:11 WARN]: 	at ServerSystem.jar//me.entity303.serversystem.utils.versions.VersionStuff$MethodOrField.<init>(VersionStuff.java:523)
[16:00:11 WARN]: 	at ServerSystem.jar//me.entity303.serversystem.utils.versions.VersionStuff.inject(VersionStuff.java:246)
[16:00:11 WARN]: 	at ServerSystem.jar//me.entity303.serversystem.listener.join.JoinListener.onLogin(JoinListener.java:31)
[16:00:11 WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor96.execute(Unknown Source)
[16:00:11 WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[16:00:11 WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[16:00:11 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:00:11 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:666)
[16:00:11 WARN]: 	at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:365)
[16:00:11 WARN]: 	at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:307)
[16:00:11 WARN]: 	at net.minecraft.server.network.PlayerConnection.c(PlayerConnection.java:341)
[16:00:11 WARN]: 	at net.minecraft.network.NetworkManager.a(NetworkManager.java:577)
[16:00:11 WARN]: 	at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:232)
[16:00:11 WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1609)
[16:00:11 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:485)
[16:00:11 WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1441)
[16:00:11 WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1208)
[16:00:11 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307)
[16:00:11 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by TheBlackEntity** [comment]
I'm really sorry for not noticing this issue.

What minecraft version and server software are you using?
